<a href="https://colab.research.google.com/github/DuncanScu/Chrun_Modelling/blob/main/Churn_Model_using_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf #TensorFlow is already in GoogleColab, no need for pip

In [7]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [10]:
dataset=pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values  #1 means leave, 0 means stay

In [11]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [12]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[: , 2])

In [16]:
print(X[:, 2]) #0 for female, 1 for male

[0 0 0 ... 0 1 0]


One Hot Encoding the "Geography" column

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))


In [18]:
print(X) #France = 1 0 0, Spain = 0 0 1 Germany = 0 1 0

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

### Feature Scaling

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [27]:
print(X_train)

[[-1.01558815  1.76021608 -0.57468161 ... -1.55362351 -1.03446007
  -1.64080994]
 [ 0.98465111 -0.56811207 -0.57468161 ...  0.64365658 -1.03446007
  -0.07927152]
 [-1.01558815 -0.56811207  1.74009395 ...  0.64365658  0.96668786
  -0.99684012]
 ...
 [ 0.98465111 -0.56811207 -0.57468161 ...  0.64365658 -1.03446007
   1.4133552 ]
 [-1.01558815 -0.56811207  1.74009395 ...  0.64365658  0.96668786
   0.84496184]
 [-1.01558815  1.76021608 -0.57468161 ...  0.64365658 -1.03446007
   0.32500428]]


In [26]:
print(X_test)

[[-1.01558815  1.76021608 -0.57468161 ...  0.64365658  0.96668786
   1.61203027]
 [ 0.98465111 -0.56811207 -0.57468161 ...  0.64365658 -1.03446007
   0.49626891]
 [-1.01558815 -0.56811207  1.74009395 ...  0.64365658  0.96668786
  -0.42502785]
 ...
 [ 0.98465111 -0.56811207 -0.57468161 ...  0.64365658 -1.03446007
  -0.272747  ]
 [-1.01558815  1.76021608 -0.57468161 ...  0.64365658 -1.03446007
  -0.93306558]
 [ 0.98465111 -0.56811207 -0.57468161 ... -1.55362351 -1.03446007
  -0.47380732]]


## Part 2 - Building the ANN

### Initializing the ANN

In [28]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [29]:
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

### Adding the second hidden layer

In [30]:
ann.add(tf.keras.layers.Dense(units= 6, activation= 'relu'))

### Adding the output layer

In [31]:
ann.add(tf.keras.layers.Dense(units= 1, activation= 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

### Training the ANN on the Training set

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

### Predicting the Test set results

### Making the Confusion Matrix